// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbgegfltwjqkyeeryngg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZ2VnZmx0d2pxa3llZXJ5bmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTcwODIsImV4cCI6MjA2MjQ3MzA4Mn0.TlPMZTjnXuWEqOTki4aSTDdqagfIx7p3yeyX3dIlWto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);